//
//  Notes.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Notes: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var userId: String?
    @objc var noteId: String?
    @objc var content: String?
    @objc var creationDate: String?
    @objc var title: String?
    
    class func dynamoDBTableName() -> String {

        return "screenfree-mobilehub-477038937-Notes"
    }
    
    class func hashKeyAttribute() -> String {

        return "userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "noteId"
    }
    
    override public static func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "userId" : "userId",
               "noteId" : "noteId",
               "content" : "content",
               "creationDate" : "creationDate",
               "title" : "title",
        ]
    }
}
