//
//  UserWebsitesBlocked.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class UserWebsitesBlocked: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userId: String?
    @objc var _blocked: NSNumber?
    @objc var _blockedWebsites: [String]?
    @objc var _customBlockedWebsite: String?
    
    class func dynamoDBTableName() -> String {
        
        return "screenfree-mobilehub-477038937-userWebsitesBlocked"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_blocked" : "blocked",
            "_blockedWebsites" : "blockedWebsites",
            "_customBlockedWebsite" : "customBlockedWebsite",
        ]
    }
}
